### ISSUE TITLE
Unable to run the card on micro_8088

### ISSUE THREAD

**Issue by andykarpov** [hkzlab/ISA_8bitNetwork_8019#1]
The card somehow does not allow to start a BIOS on the micro_8088.
I've tried different jumper mode combinations of addresses, irqs, etc - didn't help.
I guess something wrong goes on the data bus, probably.
Did you tested on micro_8088 ? 
Does there some tricks may be to start it ?

**Comment by andykarpov** [comment]
BTW, the 8019as datasheet says that pin 96 should be pulled down via 27kOhm resistor, because on start it acts as input to sence 8/16 bit slot mode, but after acts as output (open collector). Could it be a problem ?

**Comment by hkzlab** [comment]
@andykarpov yup. Not only I tested it there, but I use it there. It's installed in my micro8088 unit, works just fine. I built 3 in total, all worked on that machine, at all the possible processor speeds.

The only thing I did NOT do there is flashing the card, which I did on a 286 machine.

Two things:

- I've ran into a few machines that did NOT like the card (and it's ancestor I took the schematic from, https://github.com/Manawyrm/ISA8019), but the effect was that the interrupts were not registered, the machines still worked fine.
- My micro8088 units (I have more than one) have all their slots occupied (7 board total) plus a passive terminator mounted on the underside of the backplane.

**Comment by hkzlab** [comment]
> BTW, the 8019as datasheet says that pin 96 should be pulled down via 27kOhm resistor, because on start it acts as input to sence 8/16 bit slot mode, but after acts as output (open collector). Could it be a problem ?

Can't see why. 

- It's either floating or pulled low, so no risk of shorting
- We're not doing 16bit transfers here anyway...

**Comment by andykarpov** [comment]
Thanks for the info and explanations, will try to play with the board. 
Something goes wrong somewhere :)

Another question - does the 10k pullups for the jumpers are critical ? My board has 12k pullups instead of 10k.
The documentation says that there are 100k pulldowns inside the chip to detect the jumpers settings.
Also, does the board should start without the eeprom ?
I've already tried with and without - still no luck.

BTW, does the ISA bus terminators are necessary for this project? Does they improve something ? Could you please point me the right directions ? :)

**Comment by hkzlab** [comment]
> does the 10k pullups for the jumpers are critical ? My board has 12k pullups instead of 10k
Absolutely shouldn't be an issue. There is a lot of leeway there.

> Also, does the board should start without the eeprom ?
Which EEPROM?
The big DIP one? Yup, that is entirely optional. I'm not using it in the board I have in use currently.

The small AT94C46? Nope you need that. And you need that thing programmed to work. See instructions here: https://github.com/Manawyrm/ISA8019
As I mentioned previously, I did not try to plug it unprogrammed in the micro 8088, as I used another machine to program the cards. Have you anything else with an ISA bus to plug it in and try to program it?

> BTW, does the ISA bus terminators are necessary for this project? Does they improve something ? Could you please point me the right directions ? :)
No, not necessary. They are useful once you have many cards on the bus and you start getting interference, which generally leads to instability, especially at high clock speeds. There are active terminators, passive terminators, some backplanes even have them builtin (simple resistor dividers on the lines)...

Can't help much more than this though, certainly can't do remote troubleshooting, as, in the last year, my hobby-time has grown (or should I say shriveled?) very, very thin.

**Comment by andykarpov** [comment]
Thank you very much, @hkzlab, will try to follow the instructions from the ISA8019 project to program 93C46 eeprom :)
I guess that is the problem.

**Comment by andykarpov** [comment]
Found an issue on the PCB:
The line **ISA_IRQ6** should be disconnected from the chip to work on the **micro_8088** project normally.
After cutting the trace everything goes normally.
BTW, just comparing your schematics with the @skiselev - found that his design using less IRQ lines.

**Comment by hkzlab** [comment]
@andykarpov this does not explain why my board work with the micro8088 with the IRQ6 line in place, and I have tried multiple micro8088 builds with multiple builds of this card...
Is this happening even if you configure the card to use jumpers and set it to use something between 2 and 5? 

Have a look at the datasheet at page 19: "All unselected interrupt lines will be tri-stated". The line connected to IRQ6 should be disconnected if the board is configured as above.

I can only see a possibility here: you have a solder speck/bridge on the IRQ6 pin of the RTL8019 chip (pin 100) and is firing an interrupt when it should not. Or maybe a faulty chip in respect to that line, which is not tristating the interrupt line correctly. If you have the instrumentation you could try probing that line and see if there is activity when it should be just floating.

That said, I think I will do the following, to stay on the safe side:

1. Mention this incident in the README
2. Maybe add jumpers to disconnect IRQs 6,7,12,15

**Comment by andykarpov** [comment]
@hkzlab , well, no ideas what's going on on the IRQ6/7 lines when powering up the board. Probably it interfered somehow with the system before it actually starts and reads the jumper settings, no ideas yet. Good point to see what's happen there with the oscilloscope, will try to do that.

BTW, the problem seems reproducible not only with my board, but also on my friend's board. Chips are from the different batches as well. 

How to explain that your boards are working fine with the micro_8088 - well, may be bad soldering somewhere in between pin 99-100 ? :))) You told that you have a few problematic boards - just try to up their 99 and 100 pins and see if it helps or not. 

There are no solder bridges on any pins on my board, i've inspected everything with the multimeter and glasses. Bad RTL8019 chip - may be, but finally it just works :)

Anyway, thanks a lot for your help and support!

**Comment by hkzlab** [comment]
@andykarpov nah, the other motherboards which had issues with this board (which were not causing the board not to boot, just the IRQs were ignored) were also tested with the original Manawyrm board, which has IRQ6 and 6 disconnected, and showed the same issue.

As it happens on your friend's board too, then I'm beginning to suspect that the lines, even though tri-stated, are picking up noise (by the board itself maybe), and I'm not seeing this issue because my backplane has termination resistors that reduce noise a bit.
That said, better safe than sorry: uploaded revision 2.3 of the board that makes the lines disconnected by default and jumperable if needed, also added the warning on the README.

Let me know how the probing goes!

**Comment by hkzlab** [comment]
In the meantime, closing this as it was solved with a hardware hack that is now included in a new board revision.
