### ISSUE TITLE
UMB support

### ISSUE THREAD

**Issue by Maxx1234** [hkzlab/ISA_8bitNetwork_8019#2]
Hello!

After browsing through this thread: https://forum.vcfed.org/index.php?threads/pc-dos-3-2-for-5150.78476/
I found that this card is capable of supporting SRAM chips (after crosswiring pins 29 & 31) and can actually provide UMBs when using the RTL2UMB utility.

Successfully tested and stable on my Juko ST-12 (ROM setting: 64K @ D000-E000, Chip: AS6C4008-55PCN, crosswired pins 29 & 31).

As VCFED user Eudimorphodon recommended, a new board revision supporting jumper selection between FLASH and SRAM chips would be very interesting.

Thank you for your interesting projects!

Best regards,
Dionisios

**Comment by hkzlab** [comment]
Well, this is interesting, thanks for letting me know. 
It's surely worth the small change!

**Comment by hkzlab** [comment]
Change implemented, revision 2.4 up. I can't currently make a run of it, so if you know anyone that does and tests it, let me know :-)

**Comment by Maxx1234** [comment]
Unfortunately I have run out of RTL8019AS (and built enough rev 2.2 boards to cover my current and future needs).  Sorry :( ...
Of course, if I ever build a new board, I will definitely test the current revision and report back.
Thanks anyway!

**Comment by hkzlab** [comment]
Ah no worries, I'm in the same situation!
Should You try, let me know!
